name = "webtools"

# 添加兼容性日期配置
compatibility_date = "2025-04-26"

# 添加自定义域名配置
routes = [
  { pattern = "cdtools.org/*", zone_name = "cdtools.org" }
]

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build"

